apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-configs
  namespace: ${NAMESPACE}
data:
  ENVIRONMENT: "${ENVIRONMENT}"
  APP_HOST: "${APP_HOST}"
  APP_PORT: "${APP_PORT}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secrets
  namespace: ${NAMESPACE}
stringData:

